/*
	Copyright 1995,1996,1997 Unitex+, ltd. Kiev, Ukraine
	Written by Oleg Smolyar
	E-mail: oleg@unitex.kiev.ua
*/
#ifndef lint
static const char rcsid[]="$Id: mess.c,v 2.2.1.1 1998/07/24 12:58:58 toor Exp toor $";
#endif

#include "ned.h"

char *pmes(int num)
{
	static char *mas[]=
	{
#ifndef ENGLDIAG
		/* 1 */  "Слишком мало памяти",
		/* 2 */  "Выбор окна с файлом",
		/* 3 */  "Выбор имени нового файла",
		/* 4 */  "Вставка символа",
		/* 5 */  "Файл уже существует!",
		/* 6 */  "Действие прервано!",
		/* 7 */  "Установить цвета по умолчанию?",
		/* 8 */  "Выберите файл",
		/* 9 */  "Не могу создать %s",
		/*10 */  "Sav",
		/*11 */  "Rep",
		/*12 */  "Mar",
		/*13 */  "Mov",
		/*14 */  "Siz",
		/*15 */  "Com",
		/*16 */  "Не могу запустить программу",
		/*17 */  "Плохой код конца программы %d",
		/*18 */  "Вы не можете редактировать этот файл!",
		/*19 */  "Для Вас этот файл закрыт даже на просмотр!",
		/*20 */  "Mod",
		/*21 */  "Ins",
		/*22 */  "Фильтр",
		/*23 */  "Запуск фильтра",
		/*24 */  "Замена подстроки",
		/*25 */  "На",
		/*26 */  "Заменить",
		/*27 */  "Не могу открыть %s",
		/*28 */  "Помощь",
		/*29 */  "Сообщение",
		/*30 */  "Ошибка!",
		/*31 */  "F1-помощь;F2-модиф.;F5-открыть;F10-выход с записью;F12-команда;",
		/*32 */  "F1-помощь;F5-открыть;F10-выход;F12-команда;",
		/*33 */  "Enter-выбор;'~'-в домашний каталог;'/'-в корень;F6-полный показ;F10-выход;",
		/*34 */  "PgUp PgDn-передвижения;Enter-замена;F4-весь файл;F10-выход",
		/*35 */  "Enter-ввод имени нового файла;F10-выход",
		/*36 */  "Enter-фильтр;F4-весь файл;F9-файл до конца;F10-выход",
		/*37 */  "F1 -помощь;F10 -выход;",
		/*38 */  "Enter -выбор окна;Del-удаление окна;F10-выход;",
		/*39 */  "Enter - выбор символа;F10-выход;",
		/*40 */  "Up Down Left Right-изменение размера или положения;F10-выход",
		/*41 */  "F1-man;F2-модиф.;F3-поиск вперед;F5-открыть;F7-новый файл;",
		/*42 */  "F1-помощь;F2-модиф.;F5-открыть;F10-уничтожить окно;F12-команда;",
		/*43 */  "Аргумент",
		/*44 */  "Fin",
		/*45 */  "Загружаем   %s",
		/*46 */  "Не  найден!",
		/*47 */  "А чего искать?",
		/*48 */  "Макрокоманда не введена!",
		/*49 */  "-Ввод макрокоманды. Окончание ввода-;Esc Esc",
		/*50 */  "Извините! Макрокоманды не могут быть вложенными",
		/*51 */  "Рамка окна при изменении размеров",
		/*52 */  "Рамка read only окна при изменении размеров",
		/*53 */  "Рамка текущего окна",
		/*54 */  "Рамка текущего только читаемого окна",
		/*55 */  "Рамка неактивного окна",
		/*56 */  "Рамка неактивного только читаемого окна",
		/*57 */  "Текст в окне",
		/*58 */  "Текст в только читаемом окне",
		/*59 */  "Фон под окнами",
		/*60 */  "Рабочее меню",
		/*61 */  "Текущая строка в рабочих меню",
		/*62 */  "Непечатный символ",
		/*63 */  "Обозначение действия внизу окна",
		/*64 */  "Обозначение клавиш в строке статуса",
		/*65 */  "Обозначение действия в строке статуса",
		/*66 */  "Строчный редактор",
		/*67 */  "Каталог в меню выбора файлов",
		/*68 */  "Файл в меню выбора файлов",
		/*69 */  "Сообщение об ошибке",
		/*70 */  "Строка пояснения при выборе из меню",
		/*71 */  "Помечаемый блок",
		/*72 */  "Меню стека команд",
		/*73 */  "Текущая строка в меню стека команд",
		/*74 */  "Символическая ссылка на каталог",
		/*75 */  "Символическая ссылка на файл",
		/*76 */  "Ожидание при переходе в другой каталог",
		/*77 */  "Подсвеченные буквы в главном меню",
		/*78 */  "Подсветка: операторы",
		/*79 */  "Подсветка: препроцессор",
		/*80 */  "Подсветка: типы переменных",
		/*81 */  "Подсветка: классы памяти",
		/*82 */  "Подсветка: имена функций",
		/*83 */  "Подсветка: фигурные скобки",
		/*84 */  "Подсветка: круглые скобки",
		/*85 */  "Подсветка: комментария",
		/*86 */  "Подсветка: кириллица",
		/*87 */  "Подсветка: кавычки",
		/*88 */  "Скрытый пункт меню",
		/*89 */  "",
		/*90 */  "",
		/*91 */  "",
		/*92 */  "",
		/*93 */  "",
		/*94 */  "",
		/*95 */  "",
		/*96 */  "",
		/*97 */  "",
		/*98 */  "",
		/*99 */  "Файл %s был изменен.",
		/*100*/  "Записать?",
		/*101*/  "Да",
		/*102*/  "Нет",
		/*103*/  "Выход",
		/*104*/  "Вы хотите закончить?",
		/*105*/  "Предел количества меток исчерпан",
		/*106*/  "Нет такой метки!",
		/*107*/  "F3-поиск назад;F8-удалить строку",
		/*108*/  "Нет описания для %s в man",
		/*109*/  "Заменить все",
		/*110*/  "Заменить эту подстроку?",
		/*111*/  "Не могу запустить shell!",
		/*112*/  "Получен сигнал %d! Ned прерван!\n",
		/*113*/  "Идет поиск! Ждите...",
		/*114*/  "Идет запись! Ждите...",
		/*115*/  "Исходный файл изменен! Желательно прекратить работу!",
		/*116*/  "Файл уже блокирован!",
		/*117*/  "Не могу открыть временный файл! Редактирование невозможно!",
		/*118*/  "Системная ошибка : ",
		/*119*/  "Исчерпан лимит открытых окон!",
		/*120*/  "Идет копирование! Ждите...",
		/*121*/  "Идет удаление! Ждите...",
		/*122*/  "Ошибка чтения!",
		/*123*/  "Идет замена! Ждите...",
		/*124*/  "Ошибка записи!",
		/*125*/  "Pg│",
		/*126*/  "Lmr",
		/*127*/  "Fm1",
		/*128*/  "Fm2",
		/*129*/  "Fm3",
		/*130*/  "Pg║",
		/*131*/  "F1-помощь;F2-модификатор;Ctrl/B-изменить режим рисования;F10-выход;",
		/*132*/  "Количество пробелов в табуляции",
		/*133*/  "Enter-изменить;F10-выход;",
		/*134*/  "Изменить цвета редактора?",
		/*135*/  "Enter-поменять цвет;F4-установить цвета по умолчанию;F10-выход;",
		/*136*/  "F5-открыть файл;F7-создать файл;",
		/*137*/  "F1-записать;F2-меню;F7-заменить;F11-фильтр;F12-выход без записи;",
		/*138*/  "F2-меню;F5-задать макро;F6-выполнить макро;F10-выход;",
		/*139*/  "F2-команда;F5-размер окна;F6-мозаика;F9-каскад;F10-выход;",
		/*140*/  "F1,F5,F6,F7-автоформатирование;F2,F3-возврат каретки;F10-выход;",
		/*141*/  "Строк",
		/*142*/  "F2-модификатор;F8-вставить пустой блок;F9-запомнить блок;F10-выход;",
		/*143*/  "F2-меню;F8-удалить блок;F10-выход;",
		/*144*/  "В текущем режиме эта команда запрещена!",
		/*145*/  "Колонка",
		/*146*/  "Enter-ввод значения;F10-выход;",
		/*147*/  "Строк в странице",
		/*148*/  "Удаленный блок",
		/*149*/  "Помеченный блок",
		/*150*/  "Enter-зафиксировать цвет;Up,Down,Right,Left-выбор цвета;F10-выход",
		/*151*/  "Вы действительно хотите отказаться от всех изменений?",
		/*152*/  "Re%c",
		/*153*/  "Режимы рисования",
		/*154*/  "Повтор",
#else
		/* 1 */  "Cannot allocate memory!",
		/* 2 */  "Select window with file",
		/* 3 */  "Select name of new file",
		/* 4 */  "Symbol",
		/* 5 */  "File exist!",
		/* 6 */  "Program aborted!",
		/* 7 */  "Change editor colors setting to default?",
		/* 8 */  "Select file",
		/* 9 */  "Unable creat %s",
		/*10 */  "Sav",
		/*11 */  "Rep",
		/*12 */  "Mar",
		/*13 */  "Mov",
		/*14 */  "Siz",
		/*15 */  "Com",
		/*16 */  "Program not found!",
		/*17 */  "Bad exit code %d",
		/*18 */  "You can't edit this file!",
		/*19 */  "You can't look this file!",
		/*20 */  "Mod",
		/*21 */  "Ins",
		/*22 */  "Filter",
		/*23 */  "Run filtr",
		/*24 */  "Replace string",
		/*25 */  "To",
		/*26 */  "From",
		/*27 */  "Unable open %s",
		/*28 */  "Help",
		/*29 */  "Message",
		/*30 */  "Error!",
		/*31 */  "F1-help;F2-modify;F3-find;F4-home;F5-open;F7-wind;F10-save & quit;F12-command;",
		/*32 */  "F1-help;F5-open;F10-exit;F12-command;",
		/*33 */  "Enter-select;'~'-home;'/'-root;F6-full view;F10-exit;",
		/*34 */  "PgUp PgDn-move;Enter-replace;F4-from begin file;F10-exit;",
		/*35 */  "Enter-new file;F10-quit;",
		/*36 */  "Enter-run filtr;F4-all file;F9-from current to end;F10-exit;",
		/*37 */  "F1-help;F10-quit;",
		/*38 */  "Enter -select window;Del-close window;F10-exit;",
		/*39 */  "Enter - select symbol;PgUpPgDn-move;F10-quit;",
		/*40 */  "UpDownLeftRight-change size or move window;F5-mode;F10-exit",
		/*41 */  "F1-man;F2-modif.;F3-find forward;F4-string;F5-open;F8-insert",
		/*42 */  "F1-help;F2-modification;F5-open;F10-close window;F12-command",
		/*43 */  "Argument",
		/*44 */  "Fin",
		/*45 */  "Load  %s",
		/*46 */  "Can't find!",
		/*47 */  "What find?",
		/*48 */  "Macro no defined!",
		/*49 */  "-Define macro. End of define-;Esc Esc",
		/*50 */  "Sorry! Macro can't be recursive",
		/*51 */  "Border of window - changing size",
		/*52 */  "Border rdonly window - changing size",
		/*53 */  "Border active window",
		/*54 */  "Border active read only window",
		/*55 */  "Border not active window",
		/*56 */  "Border not active read only window",
		/*57 */  "Text",
		/*58 */  "Text read only",
		/*59 */  "Background under windows",
		/*60 */  "Work menu",
		/*61 */  "Current string in work menu",
		/*62 */  "No print symbol",
		/*63 */  "Indication in bottom window",
		/*64 */  "Indication key in help line",
		/*65 */  "Indication mode in help line",
		/*66 */  "String editor",
		/*67 */  "Directory in menu of select files",
		/*68 */  "File in menu of select files",
		/*69 */  "Message",
		/*70 */  "Help line in main menu",
		/*71 */  "Mark block",
		/*72 */  "Menu steck commands",
		/*73 */  "Current string in menu steck command",
		/*74 */  "Symbolyc link on directory",
		/*75 */  "Symbolyc link on file",
		/*76 */  "Wait for jump in other directory",
		/*77 */  "Hot letters in main menu",
		/*78 */  "Highlight: operators",
		/*79 */  "Highlight: preprocessor",
		/*80 */  "Highlight: variable type",
		/*81 */  "Highlight: memory classes",
		/*82 */  "Highlight: functions name",
		/*83 */  "Highlight: figure brackets",
		/*84 */  "Highlight: round brackets",
		/*85 */  "Highlight: comment",
		/*86 */  "Highlight: cyrillic",
		/*87 */  "Highlight: quotation marks",
		/*88 */  "Shadow line in pop menu",
		/*89 */  "",
		/*90 */  "",
		/*91 */  "",
		/*92 */  "",
		/*93 */  "",
		/*94 */  "",
		/*95 */  "",
		/*96 */  "",
		/*97 */  "",
		/*98 */  "",
		/*99 */  "%s has been changed.",
		/*100*/  "Save?",
		/*101*/  "Yes",
		/*102*/  "No",
		/*103*/  "Cancel",
		/*104*/  "Do you want quit?",
		/*105*/  "Limit of marks is drain!",
		/*106*/  "No this mark!",
		/*107*/  "F3-find back;F8-delete strings;",
		/*108*/  "No entry for %s in the manual",
		/*109*/  "Change All",
		/*110*/  "Replace this occurence?",
		/*111*/  "Unable open shell!",
		/*112*/  "Signal %d caught! Ned killed!\n",
		/*113*/  "Search! Wait...",
		/*114*/  "Save! Wait...",
		/*115*/  "File has changed! Break session!",
		/*116*/  "File already locked!",
		/*117*/  "Can't open temporary file! Can't edit!",
		/*118*/  "System error : ",
		/*119*/  "Limit open windows excedeed!",
		/*120*/  "Copy! Wait...",
		/*121*/  "Delete! Wait...",
		/*122*/  "Read error!",
		/*123*/  "Replace! Wait...",
		/*124*/  "Write error!",
		/*125*/  "Pg│",
		/*126*/  "Lmr",
		/*127*/  "Fm1",
		/*128*/  "Fm2",
		/*129*/  "Fm3",
		/*130*/  "Pg║",
		/*131*/  "F1-help;F2-modify;F3-find;Ctrl/B-change drawing mode;F10-exit;",
		/*132*/  "Number spaces in tab",
		/*133*/  "Enter-change;F10-quit;",
		/*134*/  "Change editor colors setting?",
		/*135*/  "Enter-change color;F4-chahge editor colors to default;F10-exit;",
		/*136 */  "F5-open file;F7-creat file;",
		/*137 */  "F1-save;F2-menu;F4-zoom;F7-replace;F8-del.;F9-copy;F11-filtr;F10-exit;F12-quit",
		/*138 */  "F2-menu;F5-define macro;F6-run macro;F10-quit;F12-quit no write;",
		/*139 */  "F1-get word;F2-command;F4-to end;F6-mozaic;F8-break line;F9-cascade;F10-exit;",
		/*140 */  "F1-end fmt;F5-fmt1;F6-fmt2;F7-fmt3;F2-delpos;F3-setpos;F4-close wind.;F10-exit;",
		/*141 */  "Strings",
		/*142 */  "F2-modification;F8-insert block;F9-remember block;F10-exit;",
		/*143 */  "F2-menu;F8-delete block;F10-exit;  ",
		/*144 */  "In current mode this command prohibited!",
		/*145 */  "Column",
		/*146 */  "Enter-set variable;F10-quit;",
		/*147 */  "Strings in page",
		/*148 */  "Delete block",
		/*149 */  "Mark block",
		/*150 */  "Enter-fix color;Up,Down,Right,Left-select color;F10-exit",
		/*151 */  "You lost all changes! Reallly quit?",
		/*152*/   "Re%c",
		/*153*/   "Drawing modes",
		/*154*/   "Repeating",
#endif
	};
	return(mas[num-1]);
}
